// example-react-app/src/components/UI/select/MySelect.jsx
import React from 'react';

const MySelect = ({options, defaultOption, value, onChange}) => {
    return (
        <select
            value={value}
            onChange={event => onChange(event.target.value)}
        >
            <option disabled value="">{defaultOption}</option>
            {
                options.map(o =>
                    <option key={o.value} value={o.value}>{o.name}</option>
                )
            }
        </select>
    );
};

export default MySelect;

// bem_test/posts-project/src/components/UI/MySelect.vue
<template>
    <select v-bind="{
             ...$attrs,
             onChange: (event) => $emit('update:modelValue', event.target.value)}"
              @change="changeOption">
        <option v-for="option in selectOptions"
            :key="option.value"
            :value="option.value">{{option.name}}</option>
    </select>
</template>

<script>
    export default {
        name: 'MySelect',
        props: {
            modelValue: String,
            selectOptions: {
                type: Array,
                default: () => []
            }
        },
        methods: {
            changeOption(event) {
                this.$emit('update:modelValue', event.target.value)
            }
        },
        created() {
            console.log(this.selectOptions)
        }
    }
</script>

<style lang="less" scoped>

</style>
